name: TechCovered
description: The Technology Blog
timezone: Asia/Kolkata
encoding: utf-8
permalink: /:title
paginate: 10
paginate_path: "page/:num"
highlighter: pygments
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
